/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.musicapp;

/**
 *
 * @author Administrator
 */
public class GUIClient extends javax.swing.JFrame {

    /**
     * Creates new form GUIMain
     */
    public GUIClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mainHeader = new javax.swing.JLabel();
        createPlaylistBtn = new javax.swing.JButton();
        likeSongsPanel = new javax.swing.JPanel();
        artistNameLabel = new javax.swing.JLabel();
        artistTitleLabel = new javax.swing.JLabel();
        artistGenreLabel = new javax.swing.JLabel();
        artistNameInput = new javax.swing.JTextField();
        artistTitleInput = new javax.swing.JTextField();
        addSongBtn = new javax.swing.JButton();
        artistGenreInput = new javax.swing.JComboBox<>();
        likedSongsJList = new javax.swing.JScrollPane();
        likedSongsList = new javax.swing.JList<>();
        addSongsGenreBtn = new javax.swing.JButton();
        genreAPlaylistJList = new javax.swing.JScrollPane();
        genreAdisplay = new javax.swing.JList<>();
        genreBPlaylistJList = new javax.swing.JScrollPane();
        genreBdisplay = new javax.swing.JList<>();
        moveBotoomGenreABtn = new javax.swing.JButton();
        searchGenreABtn = new javax.swing.JButton();
        deleteGenreABtn = new javax.swing.JButton();
        moveTopGenreABtn = new javax.swing.JButton();
        searchInputGenreA = new javax.swing.JTextField();
        searchArtistLabelGenreA = new javax.swing.JLabel();
        showSizeLikedListBtn = new javax.swing.JButton();
        showSizeGenreABtn = new javax.swing.JButton();
        moveBotoomGenreBBtn = new javax.swing.JButton();
        searchGenreBBtn = new javax.swing.JButton();
        deleteGenreBBtn = new javax.swing.JButton();
        moveTopGenreBBtn = new javax.swing.JButton();
        showSizeGenreBBtn = new javax.swing.JButton();
        searchInputGenreB = new javax.swing.JTextField();
        searchArtistLabelGenreB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 900));

        mainHeader.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mainHeader.setForeground(new java.awt.Color(0, 0, 0));
        mainHeader.setText("Music Application");

        createPlaylistBtn.setBackground(new java.awt.Color(0, 0, 0));
        createPlaylistBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createPlaylistBtn.setForeground(new java.awt.Color(255, 255, 255));
        createPlaylistBtn.setText("Create a Playlist");
        createPlaylistBtn.setBorderPainted(false);

        likeSongsPanel.setBackground(new java.awt.Color(204, 204, 204));
        likeSongsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Song:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        artistNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        artistNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        artistNameLabel.setText("Artist name:");

        artistTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        artistTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        artistTitleLabel.setText("Title:");

        artistGenreLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        artistGenreLabel.setForeground(new java.awt.Color(0, 0, 0));
        artistGenreLabel.setText("Genre:");

        artistNameInput.setBackground(new java.awt.Color(255, 255, 255));

        artistTitleInput.setBackground(new java.awt.Color(255, 255, 255));

        addSongBtn.setBackground(new java.awt.Color(0, 0, 0));
        addSongBtn.setForeground(new java.awt.Color(255, 255, 255));
        addSongBtn.setText("Add Song");
        addSongBtn.setBorderPainted(false);

        artistGenreInput.setBackground(new java.awt.Color(255, 255, 255));
        artistGenreInput.setForeground(new java.awt.Color(0, 0, 0));
        artistGenreInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pop", "Rap" }));

        javax.swing.GroupLayout likeSongsPanelLayout = new javax.swing.GroupLayout(likeSongsPanel);
        likeSongsPanel.setLayout(likeSongsPanelLayout);
        likeSongsPanelLayout.setHorizontalGroup(
            likeSongsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(likeSongsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(likeSongsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(artistNameLabel)
                    .addComponent(artistTitleLabel)
                    .addComponent(artistGenreLabel))
                .addGap(18, 18, 18)
                .addGroup(likeSongsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(artistGenreInput, 0, 220, Short.MAX_VALUE)
                    .addComponent(artistTitleInput)
                    .addComponent(artistNameInput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addComponent(addSongBtn)
                .addContainerGap())
        );
        likeSongsPanelLayout.setVerticalGroup(
            likeSongsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(likeSongsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(likeSongsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artistNameLabel)
                    .addComponent(artistNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(likeSongsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artistTitleLabel)
                    .addComponent(artistTitleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(likeSongsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artistGenreLabel)
                    .addComponent(artistGenreInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSongBtn))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        likedSongsList.setBackground(new java.awt.Color(204, 204, 204));
        likedSongsList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liked Songs Playlist", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        likedSongsList.setForeground(new java.awt.Color(0, 0, 0));
        likedSongsJList.setViewportView(likedSongsList);

        addSongsGenreBtn.setBackground(new java.awt.Color(0, 0, 0));
        addSongsGenreBtn.setForeground(new java.awt.Color(255, 255, 255));
        addSongsGenreBtn.setText("Add Song to Genre");
        addSongsGenreBtn.setBorderPainted(false);

        genreAdisplay.setBackground(new java.awt.Color(204, 204, 204));
        genreAdisplay.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Genre B (Rap)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        genreAdisplay.setForeground(new java.awt.Color(0, 0, 0));
        genreAPlaylistJList.setViewportView(genreAdisplay);

        genreBdisplay.setBackground(new java.awt.Color(204, 204, 204));
        genreBdisplay.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Genre A (Pop)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        genreBdisplay.setForeground(new java.awt.Color(0, 0, 0));
        genreBPlaylistJList.setViewportView(genreBdisplay);

        moveBotoomGenreABtn.setBackground(new java.awt.Color(0, 0, 0));
        moveBotoomGenreABtn.setForeground(new java.awt.Color(255, 255, 255));
        moveBotoomGenreABtn.setText("MoveBottom");
        moveBotoomGenreABtn.setBorderPainted(false);

        searchGenreABtn.setBackground(new java.awt.Color(0, 0, 0));
        searchGenreABtn.setForeground(new java.awt.Color(255, 255, 255));
        searchGenreABtn.setText("Search");
        searchGenreABtn.setBorderPainted(false);

        deleteGenreABtn.setBackground(new java.awt.Color(0, 0, 0));
        deleteGenreABtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteGenreABtn.setText("Delete");
        deleteGenreABtn.setBorderPainted(false);

        moveTopGenreABtn.setBackground(new java.awt.Color(0, 0, 0));
        moveTopGenreABtn.setForeground(new java.awt.Color(255, 255, 255));
        moveTopGenreABtn.setText("MoveTop");
        moveTopGenreABtn.setBorderPainted(false);

        searchInputGenreA.setBackground(new java.awt.Color(204, 204, 204));

        searchArtistLabelGenreA.setForeground(new java.awt.Color(0, 0, 0));
        searchArtistLabelGenreA.setText("Search by Artist:");

        showSizeLikedListBtn.setBackground(new java.awt.Color(0, 0, 0));
        showSizeLikedListBtn.setForeground(new java.awt.Color(255, 255, 255));
        showSizeLikedListBtn.setText("Show Size of Playlist");
        showSizeLikedListBtn.setBorderPainted(false);

        showSizeGenreABtn.setBackground(new java.awt.Color(0, 0, 0));
        showSizeGenreABtn.setForeground(new java.awt.Color(255, 255, 255));
        showSizeGenreABtn.setText("Show Size");
        showSizeGenreABtn.setBorderPainted(false);

        moveBotoomGenreBBtn.setBackground(new java.awt.Color(0, 0, 0));
        moveBotoomGenreBBtn.setForeground(new java.awt.Color(255, 255, 255));
        moveBotoomGenreBBtn.setText("MoveBottom");
        moveBotoomGenreBBtn.setBorderPainted(false);

        searchGenreBBtn.setBackground(new java.awt.Color(0, 0, 0));
        searchGenreBBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchGenreBBtn.setText("Search");
        searchGenreBBtn.setBorderPainted(false);

        deleteGenreBBtn.setBackground(new java.awt.Color(0, 0, 0));
        deleteGenreBBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteGenreBBtn.setText("Delete");
        deleteGenreBBtn.setBorderPainted(false);

        moveTopGenreBBtn.setBackground(new java.awt.Color(0, 0, 0));
        moveTopGenreBBtn.setForeground(new java.awt.Color(255, 255, 255));
        moveTopGenreBBtn.setText("MoveTop");
        moveTopGenreBBtn.setBorderPainted(false);

        showSizeGenreBBtn.setBackground(new java.awt.Color(0, 0, 0));
        showSizeGenreBBtn.setForeground(new java.awt.Color(255, 255, 255));
        showSizeGenreBBtn.setText("Show Size");
        showSizeGenreBBtn.setBorderPainted(false);

        searchInputGenreB.setBackground(new java.awt.Color(204, 204, 204));

        searchArtistLabelGenreB.setForeground(new java.awt.Color(0, 0, 0));
        searchArtistLabelGenreB.setText("Search by Artist:");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(mainHeader))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(createPlaylistBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(likeSongsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(likedSongsJList, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(showSizeLikedListBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addSongsGenreBtn))
                                    .addComponent(genreBPlaylistJList, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addComponent(searchArtistLabelGenreB, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(searchInputGenreB, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(searchGenreBBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(deleteGenreBBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(showSizeGenreBBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(moveTopGenreBBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(moveBotoomGenreBBtn))
                                .addComponent(genreAPlaylistJList, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(searchArtistLabelGenreA, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchInputGenreA, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchGenreABtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteGenreABtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showSizeGenreABtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moveTopGenreABtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moveBotoomGenreABtn)))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(mainHeader)
                .addGap(12, 12, 12)
                .addComponent(createPlaylistBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(likeSongsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(likedSongsJList, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSongsGenreBtn)
                    .addComponent(showSizeLikedListBtn))
                .addGap(18, 18, 18)
                .addComponent(genreBPlaylistJList, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchInputGenreA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchArtistLabelGenreA)
                    .addComponent(searchGenreABtn)
                    .addComponent(deleteGenreABtn)
                    .addComponent(moveBotoomGenreABtn)
                    .addComponent(moveTopGenreABtn)
                    .addComponent(showSizeGenreABtn))
                .addGap(18, 18, 18)
                .addComponent(genreAPlaylistJList, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchInputGenreB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchArtistLabelGenreB)
                    .addComponent(searchGenreBBtn)
                    .addComponent(deleteGenreBBtn)
                    .addComponent(moveBotoomGenreBBtn)
                    .addComponent(moveTopGenreBBtn)
                    .addComponent(showSizeGenreBBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(427, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 300, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSongBtn;
    private javax.swing.JButton addSongsGenreBtn;
    private javax.swing.JComboBox<String> artistGenreInput;
    private javax.swing.JLabel artistGenreLabel;
    private javax.swing.JTextField artistNameInput;
    private javax.swing.JLabel artistNameLabel;
    private javax.swing.JTextField artistTitleInput;
    private javax.swing.JLabel artistTitleLabel;
    private javax.swing.JButton createPlaylistBtn;
    private javax.swing.JButton deleteGenreABtn;
    private javax.swing.JButton deleteGenreBBtn;
    private javax.swing.JScrollPane genreAPlaylistJList;
    private javax.swing.JList<String> genreAdisplay;
    private javax.swing.JScrollPane genreBPlaylistJList;
    private javax.swing.JList<String> genreBdisplay;
    private javax.swing.JPanel likeSongsPanel;
    private javax.swing.JScrollPane likedSongsJList;
    private javax.swing.JList<String> likedSongsList;
    private javax.swing.JLabel mainHeader;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton moveBotoomGenreABtn;
    private javax.swing.JButton moveBotoomGenreBBtn;
    private javax.swing.JButton moveTopGenreABtn;
    private javax.swing.JButton moveTopGenreBBtn;
    private javax.swing.JLabel searchArtistLabelGenreA;
    private javax.swing.JLabel searchArtistLabelGenreB;
    private javax.swing.JButton searchGenreABtn;
    private javax.swing.JButton searchGenreBBtn;
    private javax.swing.JTextField searchInputGenreA;
    private javax.swing.JTextField searchInputGenreB;
    private javax.swing.JButton showSizeGenreABtn;
    private javax.swing.JButton showSizeGenreBBtn;
    private javax.swing.JButton showSizeLikedListBtn;
    // End of variables declaration//GEN-END:variables
}
